config/routes.rb
Rails.application.routes.draw do
  resources :employee_details
  root 'employee_details#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
  validates :Name, presence: true
  validates_numericality_of :Age, :greater_than => 18 
  #validates :Gender, presence:true
  #validates :Role, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController
  before_action :set_employee_detail, only: [:show, :edit, :update, :destroy]

  # GET /employee_details
  # GET /employee_details.json
  def index
    @employee_details = EmployeeDetail.all
  end

  # GET /employee_details/1
  # GET /employee_details/1.json
  def show
  end

  # GET /employee_details/new
  def new
    @employee_detail = EmployeeDetail.new
  end

  # GET /employee_details/1/edit
  def edit
  end

  # POST /employee_details
  # POST /employee_details.json
  def create
    @employee_detail = EmployeeDetail.new(employee_detail_params)

    respond_to do |format|
      if @employee_detail.save
        format.html { redirect_to @employee_detail, notice: 'Employee detail was successfully created.' }
        format.json { render :show, status: :created, location: @employee_detail }
      else
        format.html { render :new }
        format.json { render json: @employee_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_details/1
  # PATCH/PUT /employee_details/1.json
  def update
    respond_to do |format|
      if @employee_detail.update(employee_detail_params)
        format.html { redirect_to @employee_detail, notice: 'Employee detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_detail }
      else
        format.html { render :edit }
        format.json { render json: @employee_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_details/1
  # DELETE /employee_details/1.json
  def destroy
    @employee_detail.destroy
    respond_to do |format|
      format.html { redirect_to employee_details_url, notice: 'Employee detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_detail
      @employee_detail = EmployeeDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_detail_params
      params.require(:employee_detail).permit(:Name, :Age, :Gender, :Role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/views/employee_details/_form.html.erb
<%= form_with(model: employee_detail, local: true) do |form| %>
  <% if employee_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_detail.errors.count, "error") %> prohibited this employee_detail from being saved:</h2>

      <ul>
      <% employee_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name, id: :employee_detail_Name %>
  </div>

  <div class="field">
    <%= form.label :Age %>
    <%= form.number_field :Age, id: :employee_detail_Age %>
  </div>

  <div class="field">
    <%= form.label :Gender %>
    <%= form.select :from, [ 'Male','Female'], :prompt => 'Select One' %>
  </div>

  <div class="field">
    <%= form.label :Role %>
    <%= form.select :from, [ 'Developer','Tester','Manager'], :prompt => 'Select role' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employee_details/edit.html.erb
<h1>Editing Employee Detail</h1>

<%= render 'form', employee_detail: @employee_detail %>

<%= link_to 'Show', @employee_detail %> |
<%= link_to 'Back', employee_details_path %>

app/views/employee_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Details</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_details.each do |employee_detail| %>
      <tr>
        <td><%= employee_detail.Name %></td>
        <td><%= employee_detail.Age %></td>
        <td><%= employee_detail.Gender %></td>
        <td><%= employee_detail.Role %></td>
        <td><%= link_to 'Show', employee_detail %></td>
        <td><%= link_to 'Edit', edit_employee_detail_path(employee_detail) %></td>
        <td><%= link_to 'Destroy', employee_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Detail', new_employee_detail_path %>

app/views/employee_details/new.html.erb
<h1>New Employee Detail</h1>

<%= render 'form', employee_detail: @employee_detail %>

<%= link_to 'Back', employee_details_path %>

app/views/employee_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee_detail.Name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee_detail.Age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @employee_detail.Gender %>
</p>

<p>
  <strong>Role:</strong>
  <%= @employee_detail.Role %>
</p>

<%= link_to 'Edit', edit_employee_detail_path(@employee_detail) %> |
<%= link_to 'Back', employee_details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>